### PR TITLE
nix 2.4

### PR DESCRIPTION
**Pull request by yjftsjthsd-g**
bump NIX_VERSION from 2.3.15 to 2.4

### CODE REVIEW

**Comment by matttrach** [comment]
why hasn't this merged?

**Comment by nikolaishields** [comment]
This is an easy win, any chance we can get this merged?

**Comment by mausch** [comment]
Would be good to also include `experimental-features = nix-command flakes` in this change.

**Comment by garbas** [comment]
The work in #31 was upstreamed to `nixos/nix` repository and now images are going to build & pushed from that repository.

I just pushed `2.5.0` version to docker hub, I'll push 2.4 later today.

**Pull request closed without merging**
