### PR TITLE
Minimize closure with `keep-derivations = false`

### PR DESCRIPTION
**Pull request by Infinisil**
If this is not done, nix-shell tries to use <nixpkgs> in NIX_PATH to get
a bash, which is a problem if that doesn't exist.

Also because `nix-shell` doesn't gcroot the bash it uses from `<nixpkgs>`, this can lead to it having to build/fetch bash first before it can start, which slows it down a couple seconds.

This increases the image size from 161MB to 175MB (~8%), but considering that bash is something almost always needed I think this is reasonable.

This PR is sponsored by [Niteo](https://niteo.co/) :sparkles:

### CODE REVIEW

**Comment by peti** [comment]
I have mixed feelings about this change. My intention with this image has always been to provide the smallest possible working `nix` installation. An image that's particularly well suited for, say, interactive shell use I'd rather define separately on top of this one.

**Comment by Infinisil** [comment]
Apparently there are 2 glibc's in the closure, one of which comes from this installed bash and another from the installed Nix. I'll try to figure out how both can use the same glibc to decrease closure size.

**Comment by Infinisil** [comment]
I was able to minimize closure size from 161MB to 149MB, while adding bash at no extra cost :)

This is done by:
- Using `keep-derivations = false`
- Reinstalling Nix and cacert from the available channel to share dependencies with other things installed from the channel

See commits for more details

**Comment by Infinisil** [comment]
After thinking about it some more, what you suggested sounds fine to me. I removed all but the first commit which minimizes the closure a bit more.

**Comment by Infinisil** [comment]
Ping?

**Comment by peti** [comment]
Sorry for being unresponsive. I have a bad cold and can't do much productive work at the moment. Give me another day or two, please, then I'll revisit this PR!

**Comment by garbas** [comment]
With the work in #31 (which was upstreamed to `nixos/nix`) I think this PR becomes obsolete.

We can look at the closure size of `nixos/nix` docker image as we would for any other nix derivation. But since we are using multi layered image I'm not sure the size matters as much as it did before.

**Pull request closed without merging**
